backend:
  name: git-gateway
  branch: master

media_folder: "hugo/static/assets/uploads"
public_folder: "assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "hugo/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "object", fields: [
              {label: "Classes", name: "classes", widget: "string"},
              {label: "Background", name: "background", widget: "image"},
              {label: "Hero", name: "hero", widget: "markdown"}
            ]}
          - {label: "Footer", name: "footer", widget: "object", fields: [
              {label: Classes, name: "classes", widget: "string"}
            ]}
          - {label: "What Is", name: "whatis", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"},
              {label: "Button", name: "button", widget: "object", fields: [
                {label: "URL (inc. http://)", name: "url", widget: "string"},
                {label: "Text", name: "text", widget: "string"}
              ]}
            ]}
          - {label: "Who", name: "who", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}
          - {label: "How", name: "how", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: "string"},
              {label: "Body", name: "body", widget: "markdown"}
            ]}